<a href="https://colab.research.google.com/github/LuanaGoncalves177/Linguagem_Python_Colab/blob/main/An%C3%A1lise_de_Scores_de_Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Análise de clientes
#Nota de crédito Score de Clientes
  #Bom (Good), okay(standart) ou ruim (poor)

# Passo a passo do projeto
  # 0. Entender o desafio da empresa: finir o objetivo final do projeo
  # 1. Importar a base e dados para tratamento

#pip install pandas scikit-learn - terminal

import pandas as pd

tabela =pd.read_csv("clientes.csv")
display(tabela)
display(tabela.info())

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,alto_gasto_pagamento_baixos,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,baixo_gasto_pagamento_alto,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,baixo_gasto_pagamento_medio,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,baixo_gasto_pagamento_baixo,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,alto_gasto_pagamento_medio,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,alto_gasto_pagamento_alto,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,alto_gasto_pagamento_medio,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,alto_gasto_pagamento_alto,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,baixo_gasto_pagamento_alto,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,alto_gasto_pagamento_medio,393.673696,Poor,1,0,0,0,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB

None

In [ ]:
  # 2. Tratar a base de dados para as IAs: Preparar o padrão - prever a coluna Score de crédito

    # Tratar na tabelas o valores que são testos (transfomar em números)
      #profissao
from sklearn.preprocessing import LabelEncoder

codificador_profissao = LabelEncoder()
tabela["profissao"] = codificador_profissao.fit_transform(tabela['profissao'])

      # mix_credito
codificador_mix_credito = LabelEncoder()
tabela["mix_credito"] = codificador_mix_credito.fit_transform(tabela['mix_credito'])

      #comportamento_pagamento
codificador_comportamento_pagamento = LabelEncoder()
tabela["comportamento_pagamento"] = codificador_comportamento_pagamento.fit_transform(tabela['comportamento_pagamento'])

display(tabela)
# inversão números para textos - Não inverte os valores
# codificador_profissao.inverse_transform( y=tabela["profissao"])
# display(tabela)
      # precisão da coluna "Score_credito"

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,1,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,3,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,5,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,2,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,4,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,2,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,2,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,11,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,0,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,2,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,11,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,0,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,11,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,3,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,2,393.673696,Poor,1,0,0,0,1

Here's how you can use `inverse_transform` correctly to see the original text values for 'profissao', 'mix_credito', and 'comportamento_pagamento':

In [ ]:
# Como criar um proceso de IA
  # prever a coluna de "score_credito"

#y: O que se quer prever - "score_credito"
y = tabela["score_credito"]

#x: usar para fazer a previsão
x = tabela.drop(columns=["score_credito", "id_cliente"])

# Dvisão ds dados para texte e previsão
from sklearn.model_selection import train_test_split
x_treino, x_textest, y_treino, y_teste = train_test_split(x,y, test_size=0.3)
#70/30

In [ ]:
  # 3. Criar os modelos de previsão -> ruim, okay ou bom
#3.1. Importar a IA (Modelo)
# Árvore e descisão -> RandonFlorest e # KNN -> K Nearest Neighbors ( visinhos próximos)
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

#3.2. Criar a IA (Modelo)
modelo_arvore_decisao =RandomForestClassifier()
modelo_knn = KNeighborsClassifier()

#3.1. Treinar a IA (Modelo)
modelo_arvore_decisao.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

In [ ]:
  # 4. Avaliar e escolher o melhor modelo

  # 4.1 Previsão
previsao_arvore = modelo_arvore_decisao.predict(x_textest)
previsao_knn = modelo_knn.predict(x_textest)

  # 4. 2 Comparação entre a pevião e o y_teste
from sklearn.metrics import accuracy_score

In [ ]:
#5. Fazer novas previsões

#Árvore de decisão é o melhor modelo

#5.1 Importar novos clientes
novos_clientes = pd.read_csv("novos_clientes.csv")
display(novos_clientes)

      #profissao
novos_clientes["profissao"] = codificador_profissao.transform(novos_clientes['profissao'])

      # mix_credito
novos_clientes["mix_credito"] = codificador_mix_credito.transform(novos_clientes['mix_credito'])

      #comportamento_pagamento
novos_clientes["comportamento_pagamento"] = codificador_comportamento_pagamento.transform(novos_clientes['comportamento_pagamento'])

previsao = modelo_arvore_decisao.predict(novos_clientes)
display(novos_clientes)
display(previsao)

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,empresario,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,baixo_gasto_pagamento_baixo,312.487689,1,1,0,0,0
1,4,32.0,advogado,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,baixo_gasto_pagamento_medio,300.994163,0,0,0,0,1
2,2,48.0,empresario,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,baixo_gasto_pagamento_alto,345.081577,0,1,0,1,0

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,5,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,4,312.487689,1,1,0,0,0
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,5,300.994163,0,0,0,0,1
2,2,48.0,5,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,3,345.081577,0,1,0,1,0

array(['Poor', 'Poor', 'Standard'], dtype=object)